FORMAT: 1A
HOST: https://journey-diary.org/

# Journey Diary

Journey Diary is a back-end that would be the back-end service of 
some websites that divide journeys in articles.

## Link Relations

TODO: correct with the graph

Section describing the relations linking the different concepts of the API.

### users-all
Entry point of the API, leads to the list of users of the API

### item
Leads to the informations of one item of the collection

### up
Leads to a collection from an item

### edit
Control to edit an item

### delete
Control to delete an item

### add
Control to add an item to a collection

# Group User

## Profile

### Description
An User represent an User in the database. You can easily get the informations about the user.

### Related Profile
 - *Journey*
 
### Link relations
 - **journeys-by**: List all the journeys made by users. Can be accessed by GET.
 
### Semantic descriptors
 - **id**: INT. User’s id number.
 - **username**: STRING. User’s username
 - **password**: STRING. User’s password
 - **email**: STRING. User’s email address
 
## Users Collection [/users]

### List All Users [GET]
You can list all the Users of the database.
+ Response 200 (application/json)

        {
           "@controls":{
              "self":{
                 "href":"/api/users/"
              },
              "add-user":{
                 "href":"/api/users/",
                 "method":"POST",
                 "encoding":"json",
                 "title":"Add user to the Journey Diary API",
                 "schema":{
                    "type":"object",
                    "required":[
                       "username",
                       "password",
                       "email"
                    ],
                    "properties":{
                       "username":{
                          "description":"Username of the account",
                          "type":"string"
                       },
                       "password":{
                          "description":"Password of the account",
                          "type":"string"
                       },
                       "email":{
                          "description":"Email of the account",
                          "type":"string"
                       }
                    }
                 }
              }
        },
              "items":[
                 {
                    "username":"maellamaella",
                    "@controls":{
                       "self":{
                          "href":"/api/users/20"
                       }
                    }
                 },
                 {
                    "username":"remiviotty",
                    "@controls":{
                       "self":{
                          "href":"/api/users/21"
                       }
                    }
                 },
                 {
                    "username":"radek",
                    "@controls":{
                       "self":{
                          "href":"/api/users/22"
                       }
                    }
                 }
              ]
           }

### Create a New User [POST]
You can create a new User in the API. It takes a JSON
object containing the username, the email and the password.

+ Request (application/json)

        {
            "username": "newUser",
            "email": "newmail@mail.com",
            "password":"newpassword123"
        }

+ Response 201 (application/json)

            {
                "@controls":{
                    "self":{
                        "href":"/api/users/"
                    },
                    "get-users":{
                        "href":"/api/users/",
                        "method":"GET",
                        "encoding":"json",
                        "title":"Get list of users of the Journey Diary API"
                    }
                }
            }
            
+ Response 400
    Returned if a Username already taken
    + Body


## User Item [/users/{user}]
+ Parameters
    + user - Id of the user

### Get informations about one User [GET]
You can get the informations about one User in the API.
+ Response 200 (application/json)
            {
                "@controls": {
                    "self": {
                        "href": "/api/users/20",
                        "method": "GET"
                    },
                    "modify-user": {
                        "href": "/api/users/20",
                        "method": "PUT",
                        "encoding": "json",
                        "title": "Modify one user to the Journey Diary API",
                        "schema": {
                            "type": "object",
                            "required": [
                                "username",
                                "password",
                                "email"
                            ],
                            "properties": {
                                "username": {
                                    "description": "Username of the account",
                                    "type": "string"
                                },
                                "email": {
                                    "description": "Email of the account",
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "delete-user": {
                        "href": "/api/users/20",
                        "method": "DELETE",
                        "encoding": "json",
                        "title": "Delete one user of the Journey Diary API"
                    }
                },
                "username": "maellamaella",
                "email": "mail@gmail.com"
            }

+ Response 404 (application/json)
    Returned if trying to access one User that does not exist.
    + Body

### Modify informations about one User [PUT]
You can modify the informations about one User in the API. It takes a JSON
object containing the username, the email and the password.
+ Request (application/json)

        {
            "username": "newUser",
            "email": "newmail@mail.com",
            "password":"newpassword123"
        }

+ Response 200 (application/json)

    
            {
                "@controls": {
                    "self": {
                        "href": "/api/users/20",
                        "method": "PUT"
                    },
                    "get-user": {
                        "href": "/api/users/20",
                        "method": "GET",
                        "encoding": "json",
                        "title": "Get informations about one user to the Journey Diary API",
                    },
                    "delete-user": {
                        "href": "/api/users/20",
                        "method": "DELETE",
                        "encoding": "json",
                        "title": "Delete one user of the Journey Diary API"
                    }
                }
            }


+ Response 404 (application/json)
    Returned if trying to modify one User that does not exist.
    + Body

### Delete one User [DELETE]
You can delete one User in the API.
    

+ Response 200 (application/json)

    
            {
                "@controls": {
                    "self": {
                        "href": "/api/users/20"
                        "method": "DELETE"
                    },
                    "modify-user": {
                        "href": "/api/users/20",
                        "method": "PUT",
                        "encoding": "json",
                        "title": "Modify one user to the Journey Diary API",
                        "schema": {
                            "type": "object",
                            "required": [
                                "username",
                                "password",
                                "email"
                            ],
                            "properties": {
                                "username": {
                                    "description": "Username of the account",
                                    "type": "string"
                                },
                                "email": {
                                    "description": "Email of the account",
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "get-user": {
                        "href": "/api/users/20",
                        "method": "GET",
                        "encoding": "json",
                        "title": "Get informations about one user to the Journey Diary API",
                    }
                }
            }


+ Response 404 (application/json)
    Returned if trying to delete one User that does not exist.
    + Body

# Group Journey

## Profile

### Description
A Journey represent a Journey Item in the database. You can easily get the informations about the journey and the different days of the journey.

### Related Profile
 - *DaysByJourneys*
 
### Link relations
 - **days-by**: List all the days included in that journey.
 - **up**: List all the journeys collection, where's that journey belongs.
 
### Semantic descriptors
 - **id**: INT. Journey’s id number.
 - **user_id**: INT. User’s id number
 - **title**: STRING. Journey’s title.

## Journeys by User [/users/{user}/journeys]
+ Parameters
    + user - Id of the user

### List of Journeys by User [GET]
You can list all the Users of the database linked to one User.

+ Response 200 (application/json)
    
    {
        "@controls":{
            "self":{
                "href":"/api/users/1/journeys/"
            },
            "add-journey":{
                "href":"/api/users/1/journeys/",
             "method":"POST",
             "encoding":"json",
             "title":"Add journey to the Journey Diary API",
             "schema":{
                "type":"object",
                "required":[
                   "title",
                   "description",
                ],
                "properties":{
                   "title":{
                      "description":"Title of the journey",
                      "type":"string"
                   }
                }
         }
      }
    },
      "items":[
         {
            "title":"1st Journey",
            "@controls":{
               "self":{
                  "href":"/api/users/1/journeys/1"
               }
            }
         },
         {
            "title":"2nd Journey",
            "@controls":{
               "self":{
                  "href":"/api/users/1/journeys/2"
               }
            }
         },
         {
            "title":"3rd journey",
            "@controls":{
               "self":{
                  "href":"/api/users/1/journeys/3"
               }
            }
         }
      ]
   }

### Create a New Journey [POST]
You can create a new Journey in the API. It takes a JSON
object containing the title and the description.

+ Request (application/json)

        {
            "title": "Test"
        }

+ Response 201 (application/json)

        {
             "@controls":{
                    "self":{
                        "href":"/api/users/1/journeys/"
                    },
                    "get-journeys":{
                        "href":"/api/users/1/journeys/",
                        "method":"GET",
                        "encoding":"json",
                        "title":"Get list of journeys of the Journey Diary API"
                    }
                }
            }
        }
            
        

+ Response 400 (application/json)
- Journey ID already taken
 
## Journey Item [/users/{user}/journeys/{journey}/]
+ Parameters
    + user - Id of the user
    + journey - Id of the journey

### Get informations about one Journey [GET]
You can get the informations about one Journey in the API.

+ Response 200 (application/json)

    
            {
                "@controls": {
                    "self": {
                        "href": "/api/users/1/journeys/1"
                    },
                    "modify-journey": {
                        "href": "/api/users/1/journeys/1",
                        "method": "PUT",
                        "encoding": "json",
                        "title": "Modify journey to the Journey Diary API",
                        "schema": {
                            "type": "object",
                            "required": [
                                "title"
                            ],
                            "properties": {
                                "title": {
                                    "description": "Title of the journey",
                                    "type": "string"
                                }
                                
                            }
                        }
                    }
            },
            "title": "Title",
        }

+ Response 404 (application/json)
    Returned if trying to access one Journey that does not exist.
    + Body

### Modify informations about one Journey [PUT]
You can modify the informations about one Journey in the API. It takes a JSON object containing a title.

+ Request (application/json)

        {
            "title": "newTitle",
        }

+ Response 200 (application/json)

    
            {
                "@controls": {
                    "self": {
                        "href": "/api/users/20/journeys/30"
                    },
                    "modify-user": {
                        "href": "/api/users/20/journeys/30",
                        "method": "GET",
                        "encoding": "json",
                        "title": "Get informations about one journey to the Journey Diary API",
                    }
                }
            }


+ Response 404 (application/json)
    Returned if trying to modify one journey that does not exist.
    + Body

### Delete one Journey [DELETE]
You can delete one Journey in the API.

+ Response 200 (application/json)

    
            {
                "@controls": {
                    "self": {
                        "href": "/api/users/20/journeys/30"
                    },
                    "modify-user": {
                        "href": "/api/users/20/journeys/30",
                        "method": "GET",
                        "encoding": "json",
                        "title": "Get informations about one journey to the Journey Diary API",
                    }
                }
            }


+ Response 404 (application/json)
    Returned if trying to delete one journey that does not exist.
    + Body



# Group Day
## Profile
### Description
Represent one day of a journey.

### Link relations
 - **journey-of**: Journey that is related to the *Days By Journey*.
 - **images-by**: *Images By Day* that are related to this day.
 
### Semantic descriptors
 - **date**: *Date* Date of the day. 
 - **description**: *String* Description of the day. 

## Days By Journey [/users/{user}/journeys/{journey}/days]
+ Parameters
    + user - Id of the user
    + journey - Id of the journey

### List of Days by Journey [GET]
You can list all the Days of the database linked to one Journey.

+ Response 200 (application/json)
    
    {
        "@controls":{
            "self":{
                "href":"/api/users/1/journeys/1/days",
                "method":"GET"
            },
            "add":{
                "href":"/api/users/1/journeys/1/days",
                "method":"POST",
                "encoding":"json",
                "title":"Add a Day to the Journey Diary API",
                "schema":{
                "type":"object",
                "required":[
                   "date",
                   "description",
                ],
                "properties":{
                    "date":{
                      "description":"Date of the day",
                      "type":"date"
                    },
                    "description":{
                      "description":"Description of the Day",
                      "type":"string"
                    }
                }
            },
            "journey-of":{
                "href":"/api/users/1/journeys/1/",
                "encoding":"json",
                "title":"Journey that is related to these days"
            }
        }
    },
      "items":[
         {
            "date": "2020-03-15 18:30:00",
            "@controls":{
               "self":{
                  "href":"/api/users/1/journeys/1/days/1"
               }
            }
         },
         {
            "date": "2020-03-16 18:30:00",
            "@controls":{
               "self":{
                  "href":"/api/users/1/journeys/1/days/2"
               }
            }
         },
         {
            "date": "2020-03-17 18:30:00",
            "@controls":{
               "self":{
                  "href":"/api/users/1/journeys/1/days/3"
               }
            }
         }
      ]
   }

### Create a New Day [POST]
You can create a new Day in the API. It takes a JSON
object containing the date and the description.

+ Request (application/json)

        {
            "date": "2020-03-15 18:30:00",
            "description": "Test"
        }

+ Response 201 (application/json)

        {
             "@controls":{
                    "self":{
                        "href":"/api/users/1/journeys/1/days"
                    },
                    "get-days":{
                        "href":"/api/users/1/journeys/1/days",
                        "method":"GET",
                        "encoding":"json",
                        "title":"Get list of days of the Journey Diary API"
                    }
                }
            }
        }
            
        

+ Response 400 (application/json)
- Journey ID already taken


## Day Item [/api/users/{user}/journeys/{journey}/days/{day}/]
+ Parameters
    + user - Id of the user
    + journey - Id of the journey
    + day - Id of the day

### Get informations about one Day [GET]
You can get the informations about one Day in the API. It takes a JSON
object containing the date and the description.
+ Response 200 (application/json)
            {
                "@controls": {
                    "self": {
                        "href": "/api/users/20/journeys/30/days/1/",
                        "method": "GET"
                    },
                    "modify-day": {
                        "href": "/api/users/20/journeys/30/days/1/",
                        "method": "PUT",
                        "encoding": "json",
                        "title": "Modify one date to the Journey Diary API",
                        "schema": {
                            "type": "object",
                            "required": [
                                "date",
                                "description"
                            ],
                            "properties": {
                                "date": {
                                    "description": "Date of the day",
                                    "type": "date"
                                },
                                "description": {
                                    "description": "Description of the day",
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "delete-day": {
                        "href": "/api/users/20/journeys/30/days/1/",
                        "method": "DELETE",
                        "encoding": "json",
                        "title": "Delete one day of the Journey Diary API"
                    }
            },
            "date": "2020-03-15 18:30:00",
            "description": "Description"
        }

+ Response 404 (application/json)
    Returned if trying to access one User that does not exist.
    + Body

### Modify informations about one Day [PUT]
You can modify the informations about one Day in the API. It takes a JSON
object containing the date and a description.
+ Request (application/json)

        {
            "date": "2020-03-15 18:30:00",
            "description": "Description new"
        }

+ Response 200 (application/json)

            {
                "@controls": {
                    "self": {
                        "href": "/api/users/20/journeys/30/days/1/",
                        "method": "PUT"
                    },
                    "get-day": {
                        "href": "/api/users/20/journeys/30/days/1/",
                        "method": "GET",
                        "encoding": "json",
                        "title": "Get informations about one day to the Journey Diary API",
                    },
                    "delete-day": {
                        "href": "/api/users/20/journeys/30/days/1/",
                        "method": "DELETE",
                        "encoding": "json",
                        "title": "Delete one day of the Journey Diary API"
                    }
                }
            }


+ Response 404 (application/json)
    Returned if trying to modify one User that does not exist.
    + Body

### Delete one Day [DELETE]
You can delete one Day in the API.
    

+ Response 200 (application/json)

    
            {
                "@controls": {
                    "self": {
                        "href": "/api/users/20/journeys/30/days/1/",
                        "method": "DELETE"
                    },
                    "modify-day": {
                        "href": "/api/users/20/journeys/30/days/1/",
                        "method": "PUT",
                        "encoding": "json",
                        "title": "Modify one day to the Journey Diary API",
                        "schema": {
                            "type": "object",
                            "required": [
                                "date",
                                "description"
                            ],
                            "properties": {
                                "date": {
                                    "description": "Date of the day",
                                    "type": "date"
                                },
                                "description": {
                                    "description": "Description of the day",
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "get-day": {
                        "href": "/api/users/20/journeys/30/days/1/",
                        "method": "GET",
                        "encoding": "json",
                        "title": "Get informations about one day to the Journey Diary API",
                    }
                }
            }


+ Response 404 (application/json)
    Returned if trying to delete one Day that does not exist.
    + Body

# Group Image
## Profile
### Description
Represent one image of a day.

### Link relations
 - **day-of**: Day that is related to the *Images By Day*.
 
### Semantic descriptors
 - **extension**: *String* Extension of the image file. 

## Images By Day [/users/{user}/journeys/{journey}/days/{day}/images]
+ Parameters
    + user - Id of the user
    + journey - Id of the journey
    + day - Id of the day

### List of Images by Day [GET]
You can list all the Images of the database linked to one Day.

+ Response 200 (application/json)
    
    {
        "@controls":{
            "self":{
                "href":"/api/users/1/journeys/1/days/1/images"
            },
            "add-day":{
                "href":"/api/users/1/journeys/1/days/1/images",
                "method":"POST",
                "encoding":"json",
                "title":"Add Image to the Journey Diary API",
                "schema":{
                    "type":"object",
                    "required":[
                       "extension"
                    ],
                    "properties":{
                       "extension":{
                          "description":"Extension of the file of the image",
                          "type":"string"
                       }
                    }
                }
            }
        },
        "items":[
            {
                "@controls":{
                    "self":{
                        "href":"/api/users/1/journeys/1/days/1/images/1.png"
                    }
                }
            },
            {
                "@controls":{
                    "self":{
                        "href":"/api/users/1/journeys/1/days/1/images/2.jpg"
                    }
                }
            },
            {
                "@controls":{
                    "self":{
                        "href":"/api/users/1/journeys/1/days/1/images/3.png"
                    }
                }
            }
        ]
   }

### Create a New Image [POST]
You can create a new Image in the API. It takes a JSON
object containing the extension of the image.

+ Request (application/json)

        {
            "extension": "png"
        }

+ Response 201 (application/json)

        {
             "@controls":{
                    "self":{
                        "href":"/api/users/1/journeys/1/days/1/images"
                    },
                    "get-days":{
                        "href":"/api/users/1/journeys/1/days/1/images",
                        "method":"GET",
                        "encoding":"json",
                        "title":"Get list of images of the Journey Diary API"
                    }
                }
            }
        }
            
        

+ Response 400 (application/json)
- Journey ID already taken


## Image Item [/api/users/{user}/journeys/{journey}/days/{day}/images/{image}.{extension}]
+ Parameters
    + user - Id of the user
    + journey - Id of the journey
    + day - Id of the day
    + image - Id of the image
    + extension - Extension of the image

### Get informations about one Image [GET]
You can get the Image in the API.

+ Response 200 (application/json)
            {
                "@controls": {
                    "self": {
                        "href": "/api/users/10/journeys/20/days/30/images/40.jpg",
                        "method": "GET"
                    },
                    "modify-image": {
                        "href": "/api/users/10/journeys/20/days/30/images/40.jpg",
                        "method": "PUT",
                        "encoding": "json",
                        "title": "Modify one image to the Journey Diary API",
                        "schema": {
                            "type": "object",
                            "required": [
                                "extension"
                            ],
                            "properties": {
                                "extension": {
                                    "description": "Extension of the image",
                                    "type": "string"
                                
                                }
                            }
                        }
                    },
                    "delete-image": {
                        "href": "/api/users/10/journeys/20/days/30/images/40.jpg",
                        "method": "DELETE",
                        "encoding": "json",
                        "title": "Delete one image of the Journey Diary API"
                    }
            }
        }

+ Response 404 (application/json)
    Returned if trying to access one User that does not exist.
    + Body

### Modify informations about one Image [PUT]
You can modify the informations about one Image in the API. It takes a JSON
object containing the extension.
+ Request (application/json)

        {
            "extension": "jpg"
        }

+ Response 200 (application/json)

    
            {
                "@controls": {
                    "self": {
                        "href": "/api/users/10/journeys/20/days/30/images/40.jpg",
                        "method": "PUT"
                    },
                    "get-image": {
                        "href": "/api/users/10/journeys/20/days/30/images/40.jpg",
                        "method": "GET",
                        "encoding": "json",
                        "title": "Get one image of the Journey Diary API",
                    },
                    "delete-image": {
                        "href": "/api/users/10/journeys/20/days/30/images/40.jpg",
                        "method": "DELETE",
                        "encoding": "json",
                        "title": "Delete one image of the Journey Diary API"
                    }
                }
            }


+ Response 404 (application/json)
    Returned if trying to modify one User that does not exist.
    + Body

### Delete one Image [DELETE]
You can delete one Image in the API.
    

+ Response 200 (application/json)

    
            {
                "@controls": {
                    "self": {
                        "href": "/api/users/10/journeys/20/days/30/images/40.jpg", 
                        "method": "DELETE"
                    },
                    "modify-image": {
                        "href": "/api/users/10/journeys/20/days/30/images/40.jpg",
                        "method": "PUT",
                        "encoding": "json",
                        "title": "Modify one image to the Journey Diary API",
                        "schema": {
                            "type": "object",
                            "required": [
                                "date",
                                "description"
                            ],
                            "properties": {
                                "extension": {
                                    "description": "Extension of the image",
                                    "type": "string"

                                }
                            }
                        }
                    },
                    "get-image": {
                        "href": "/api/users/10/journeys/20/days/30/images/40.jpg",
                        "method": "GET",
                        "encoding": "json",
                        "title": "Get one image to the Journey Diary API",
                    }
                }
            }


+ Response 404 (application/json)
    Returned if trying to delete one Day that does not exist.
    + Body